### ISSUE TITLE
Add configuration or template ID to the ref URI for vms

### ISSUE THREAD

**Issue by kiminoa** [skytap/sample-api#1]
https://github.com/skytap/sample-api/blob/c39c7704dbf35d125b471ba80a57e205a657c26b/Python_2/put_vm_start.py#L44

**Comment by packetizeme** [comment]
Thank you for pointing this out @kiminoa !

Although a call to https://cloud.skytap.com/vms/<vm-id> will actually be successful it is inconsistent with Skytap's API documentation; I have fixed this in 779e456.
